// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsmvmjfjkivyrrybqrav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbXZtamZqa2l2eXJyeWJxcmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTQ0NjEsImV4cCI6MjA2ODE3MDQ2MX0.v2JORSsB_0MQlMT8AQqmkvOM0m4Gw83Gko7Pnfal26Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});